#!/usr/bin/env python3
"""
Post-correction reflection runner.
Called automatically after any user correction is handled.
Writes to the daily reflection file and updates the policy store.
"""

import json
import os
from datetime import datetime

HERMES_HOME = os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))
REFLECTION_DIR = os.path.join(HERMES_HOME, "logs", "reflection")
POLICY_DIR = os.path.join(HERMES_HOME, "policies")
FIRINGS_LOG = os.path.join(HERMES_HOME, "logs", "policy-firings.jsonl")
STATE_FILE = os.path.join(HERMES_HOME, "state", "reflect-on-correction-last-run.json")


def load_state():
    """Load last-run state: timestamp and byte cursor into firings log."""
    if os.path.exists(STATE_FILE):
        with open(STATE_FILE) as f:
            return json.load(f)
    return {"last_run": None, "last_firing_cursor": 0}


def save_state(state):
    """Persist last-run state."""
    os.makedirs(os.path.dirname(STATE_FILE), exist_ok=True)
    with open(STATE_FILE, "w") as f:
        json.dump(state, f, indent=2)


def get_new_firings(cursor):
    """
    Get policy firings since the given byte offset cursor.
    Returns (list_of_new_firings, new_cursor).
    Handles log truncation by resetting cursor to 0 if cursor > file size.
    """
    if not os.path.exists(FIRINGS_LOG):
        return [], cursor
    with open(FIRINGS_LOG) as f:
        # Handle truncation: if the file shrank, reset cursor
        f.seek(0, 2)  # end of file
        file_size = f.tell()
        if cursor > file_size:
            cursor = 0
        f.seek(cursor)
        new_lines = f.readlines()
        new_cursor = f.tell()
    return [json.loads(l) for l in new_lines], new_cursor


def load_daily_reflection():
    """Load existing reflection or create template."""
    path = os.path.join(REFLECTION_DIR, f"{datetime.now().strftime('%Y-%m-%d')}.md")
    if os.path.exists(path):
        with open(path) as f:
            return f.read(), path
    return None, path


def load_policies():
    """Load all active policies."""
    policies = []
    if not os.path.isdir(POLICY_DIR):
        return policies
    for fname in sorted(os.listdir(POLICY_DIR)):
        if fname.endswith(".json"):
            with open(os.path.join(POLICY_DIR, fname)) as f:
                policies.append(json.load(f))
    return policies


def get_recent_firings():
    """Get last 10 policy firings (for display/counts, not dedup logic)."""
    if not os.path.exists(FIRINGS_LOG):
        return []
    with open(FIRINGS_LOG) as f:
        lines = f.readlines()
    return [json.loads(l) for l in lines[-10:]]


def main():
    state = load_state()
    new_firings, new_cursor = get_new_firings(state.get("last_firing_cursor", 0))

    # No new policy firings since last run → exit silently
    if not new_firings:
        return 0

    content, path = load_daily_reflection()
    policies = load_policies()
    firings = get_recent_firings()

    now = datetime.now().strftime("%H:%M:%S")

    active_policies = [p for p in policies if p.get("status") in ("provisional", "active")]

    entry = f"""
## Auto-Reflection — {now}

**Correction handled.** Triggered by post-correction hook.

Policies in store: {len(policies)} ({len(active_policies)} active/provisional)
New firings since last run: {len(new_firings)}
Total policy firings today: {len(firings)}"""

    if new_firings:
        entry += "\n\nNew firings:\n"
        for f in new_firings[-5:]:
            entry += f"- Policy {f['policy_id']}: {f['trigger'][:60]}\n"

    # Source from real state only — no hardcoded "Policy 004 has 0 hits" claim.
    entry += "\n### Observed state\n"
    if firings:
        entry += f"{len(firings)} policy firing(s) today across {len(active_policies)} active policies.\n"
    else:
        entry += "No policy firings recorded today.\n"
    entry += "Verified self-improvement, if any, is in the evidence ledger (`coordinator.py evidence`).\n\n"

    entry += "### Hook\n"
    entry += "Post-correction reflection hook ran; observations above are from live state.\n\n"

    entry += f"--- auto-generated by reflect-on-correction hook ---\n"

    if content:
        # Append to existing reflection
        with open(path, "a") as f:
            f.write(entry)
    else:
        # Create new reflection
        with open(path, "w") as f:
            f.write(f"# Otto Daily Reflection — {datetime.now().strftime('%Y-%m-%d')}\n")
            f.write(entry)

    # Update state after successful run
    save_state({
        "last_run": datetime.now().isoformat(),
        "last_firing_cursor": new_cursor,
    })

    return 0


if __name__ == "__main__":
    exit(main())
