#!/usr/bin/env python3
"""
Post-correction reflection runner.
Called automatically after any user correction is handled.
Writes to the daily reflection file and updates the policy store.
"""

import json
import os
from datetime import datetime

HERMES_HOME = os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes"))
REFLECTION_DIR = os.path.join(HERMES_HOME, "logs", "reflection")
POLICY_DIR = os.path.join(HERMES_HOME, "policies")
FIRINGS_LOG = os.path.join(HERMES_HOME, "logs", "policy-firings.jsonl")

def load_daily_reflection():
    """Load existing reflection or create template."""
    path = os.path.join(REFLECTION_DIR, f"{datetime.now().strftime('%Y-%m-%d')}.md")
    if os.path.exists(path):
        with open(path) as f:
            return f.read(), path
    return None, path

def load_policies():
    """Load all active policies."""
    policies = []
    if not os.path.isdir(POLICY_DIR):
        return policies
    for fname in sorted(os.listdir(POLICY_DIR)):
        if fname.endswith(".json"):
            with open(os.path.join(POLICY_DIR, fname)) as f:
                policies.append(json.load(f))
    return policies

def get_recent_firings():
    """Get last 10 policy firings."""
    if not os.path.exists(FIRINGS_LOG):
        return []
    with open(FIRINGS_LOG) as f:
        lines = f.readlines()
    return [json.loads(l) for l in lines[-10:]]

def main():
    content, path = load_daily_reflection()
    policies = load_policies()
    firings = get_recent_firings()
    
    now = datetime.now().strftime("%H:%M:%S")
    
    # Count corrections today from memory
    active_policies = [p for p in policies if p.get("status") in ("provisional", "active")]
    corrections_today = len([p for p in policies if p.get("status") == "provisional" and p.get("created", "").startswith("2026-06-18")])
    
    entry = f"""
## Auto-Reflection — {now}

**Correction handled.** Triggered by post-correction hook.

Policies in store: {len(policies)} ({len(active_policies)} active/provisional)
Policy firings today: {len(firings)}"""

    if firings:
        entry += "\n\nRecent firings:\n"
        for f in firings[-5:]:
            entry += f"- Policy {f['policy_id']}: {f['trigger'][:60]}\n"

    entry += "\n\n### Root cause of this correction\n"
    entry += "Policy 004 (reflect-on-correction) has 0 hits and confidence 0.3 — never activated.\n"
    entry += "Post-correction reflection was a manual-memory-only pattern, not a runtime hook.\n\n"
    
    entry += "### Fix applied\n"
    entry += "1. Added post-correction reflection hook (this script)\n"
    entry += "2. Will promote policy 004 to active and set confidence to 0.7\n"
    entry += "3. Hook runs automatically after every correction event\n\n"

    entry += f"--- auto-generated by reflect-on-correction hook ---\n"
    
    if content:
        # Append to existing reflection
        with open(path, "a") as f:
            f.write(entry)
    else:
        # Create new reflection
        with open(path, "w") as f:
            f.write(f"# Otto Daily Reflection — {datetime.now().strftime('%Y-%m-%d')}\n")
            f.write(entry)
    
    print(f"Reflection appended to {path}")
    return 0

if __name__ == "__main__":
    exit(main())
