#!/usr/bin/env python3
"""report_generator.py — Weekly/monthly reports and ROI dashboards."""
import json, os, sys, time
from datetime import datetime, timezone, timedelta
from pathlib import Path
HERMES = Path(os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes")))

def _load_jsonl(path, hours=168):
    if not Path(path).is_file(): return []
    cutoff = datetime.now(timezone.utc) - timedelta(hours=hours)
    entries = []
    for line in Path(path).read_text().splitlines():
        if not line.strip(): continue
        try:
            e = json.loads(line)
            ts = e.get("ts") or e.get("timestamp") or ""
            if ts:
                dt = datetime.fromisoformat(str(ts).replace("Z","+00:00"))
                if dt < cutoff: continue
            entries.append(e)
        except: continue
    return entries

def roi_metrics():
    ops = _load_jsonl(HERMES/"logs"/"ops-monitor.jsonl", 168)
    auto_fixes = sum(1 for o in ops if o.get("type") in ("moat_auto_pause","moat_auto_resume"))
    
    # Incident stats
    try:
        r = subprocess_module.run([sys.executable, str(HERMES/"scripts"/"incident_manager.py"), "--stats", "--json"],
                          capture_output=True, text=True, timeout=15)
        incidents = json.loads(r.stdout) if r.stdout.strip() else {"total": 0, "resolved": 0, "auto_resolved": 0, "avg_mttr_min": 0}
    except:
        incidents = {"total": 0, "resolved": 0, "auto_resolved": 0, "avg_mttr_min": 0}
    
    ticks = Path.home()/"Documents/code/prospector/store/scheduler/ticks.jsonl"
    runs = spent = 0
    if ticks.is_file():
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        for ln in ticks.read_text().splitlines():
            try:
                t = json.loads(ln)
                if t.get("ts","").startswith(today): runs += 1; spent = max(spent, float(t.get("today_spend_usd",0) or 0))
            except: pass
    
    total_incidents = incidents.get("total", 0)
    resolved = incidents.get("resolved", 0)
    auto_resolved = incidents.get("auto_resolved", 0)
    hours_saved = auto_resolved * 0.25  # assume 15min saved per auto-fix
    ai_cost = spent
    human_cost_saved = hours_saved * 150  # $150/h engineer
    
    return {"incidents_this_week": total_incidents, "resolved": resolved, "auto_resolved": auto_resolved,
            "hours_saved": round(hours_saved, 1), "ai_spend": round(ai_cost, 2),
            "human_cost_saved": round(human_cost_saved, 2), "net_savings": round(human_cost_saved - ai_cost, 2),
            "mttr_min": incidents.get("avg_mttr_min", 0)}

def weekly_report():
    roi = roi_metrics()
    now = datetime.now(timezone.utc)
    lines = [f"📊 *Weekly Report — {now.strftime('%b %d, %Y')}*", "",
             f"*Incidents:* {roi['incidents_this_week']} total · {roi['resolved']} resolved · {roi['auto_resolved']} auto-resolved",
             f"*MTTR:* {roi['mttr_min']} min average",
             f"*Value:* {roi['hours_saved']}h saved · AI spend ${roi['ai_spend']} · Net ${roi['net_savings']:+.2f}",
             "", "*Estate:* See `status` for live health.", "",
             "_Generated by Otto — your autonomous estate manager_"]
    return "\n".join(lines)

import subprocess as subprocess_module
def subprocess_run(cmd):
    import subprocess as sp
    r = sp.run(cmd, capture_output=True, text=True, timeout=15)
    try: return json.loads(r.stdout)
    except: return {}

def main():
    import argparse
    p = argparse.ArgumentParser(description="Report generator")
    p.add_argument("--weekly", action="store_true"); p.add_argument("--roi", action="store_true")
    p.add_argument("--json", action="store_true")
    args = p.parse_args()
    r = roi_metrics()
    if args.weekly:
        r["report"] = weekly_report()
    if args.json:
        print(json.dumps(r, indent=2, default=str))
    else:
        print(json.dumps(r, indent=2, default=str))

if __name__ == "__main__": main()
